export const financialAssetTypes = {
  BOND_DURATION: "BOND_DURATION",
  BOND_RATING: "BOND_RATING",
  BOND_SECTOR_BASED: "BOND_SECTOR_BASED",
  STOCK_GEOGRAPHIC: "STOCK_GEOGRAPHIC",
  STOCK_SECTOR_BASED: "STOCK_SECTOR_BASED"
};
