export const FETCH_CURRENT_PROFILE = "FETCH_CURRENT_PROFILE";
export const SAVE_CURRENT_PROFILE = "SAVE_CURRENT_PROFILE";
export const WMP_PROFILE_ERROR = "WMP_PROFILE_ERROR";
export const VISIBILITY_CONE = "VISIBILITY_CONE";
export const BLOCKING_ALERT = "BLOCKING_ALERT";
export const NOT_BLOCKING_ALERT = "NOT_BLOCKING_ALERT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const SET_TOKEN = "SET_TOKEN";
export const LOGGING_OUT = "LOGGING_OUT";
export const LOGOUT = "LOGOUT";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_UNREAD_NOTIFICATIONS_COUNT = "SET_UNREAD_NOTIFICATIONS_COUNT";
export const SET_NOTIFICATIONS_FETCHED = "SET_NOTIFICATIONS_FETCHED";
export const SET_UNREAD_NOTIFICATIONS_COUNT_FETCHED =
  "SET_UNREAD_NOTIFICATIONS_COUNT_FETCHED";

// ActiveVisibilityCones actions

export const FETCH_ACTIVE_VISIBILITY_CONES = "FETCH_ACTIVE_VISIBILITY_CONES";
export const FETCH_ACTIVE_VISIBILITY_CONES_SUCCESS =
  "FETCH_ACTIVE_VISIBILITY_CONES_SUCCESS";
export const FETCH_ACTIVE_VISIBILITY_CONES_ERROR =
  "FETCH_ACTIVE_VISIBILITY_CONES_ERROR";

export const RESET_ACTIVE_VISIBILITY_CONES = "RESET_ACTIVE_VISIBILITY_CONES";
export const CLEAR_VISIBILITY_ERROR = "CLEAR_VISIBILITY_ERROR";
export const CLEAR_VISIBILITY_MESSAGE_ERROR = "CLEAR_VISIBILITY_MESSAGE_ERROR";
// VisibilityCones actions
export const FETCH_VISIBILITY_CONES = "FETCH_VISIBILITY_CONES";
export const FETCH_VISIBILITY_CONES_SUCCESS = "FETCH_VISIBILITY_CONES_SUCCESS";
export const FETCH_VISIBILITY_CONES_ERROR = "FETCH_VISIBILITY_CONES_ERROR";

export const POST_VISIBILITY_CONES = "POST_VISIBILITY_CONES";
export const POST_VISIBILITY_CONES_SUCCESS = "POST_VISIBILITY_CONES_SUCCESS";
export const POST_VISIBILITY_CONES_ERROR = "POST_VISIBILITY_CONES_ERROR";

// VisibilityConesMessage actions

export const FETCH_VISIBILITY_CONES_MESSAGE = "FETCH_VISIBILITY_CONES_MESSAGE";
export const FETCH_VISIBILITY_CONES_MESSAGE_SUCCESS =
  "FETCH_VISIBILITY_CONES_MESSAGE_SUCCESS";
export const FETCH_VISIBILITY_CONES_MESSAGE_ERROR =
  "FETCH_VISIBILITY_CONES_MESSAGE_ERROR";

export const POST_VISIBILITY_CONES_MESSAGE = "POST_VISIBILITY_CONES_MESSAGE";
export const POST_VISIBILITY_CONES_MESSAGE_SUCCESS =
  "POST_VISIBILITY_CONES_MESSAGE_SUCCESS";
export const POST_VISIBILITY_CONES_MESSAGE_ERROR =
  "POST_VISIBILITY_CONES_MESSAGE_ERROR";

// VisibilityCones actions
export const FETCH_NAV_URLS = "FETCH_NAV_URLS";
export const FETCH_NAV_URLS_RESPONSE = "FETCH_NAV_URLS_RESPONSE";
export const HOME_PAGE_LOADED = "HOME_PAGE_LOADED";

// Abi and Cab list
export const FETCH_ABI_LIST = "FETCH_ABI_LIST";
export const FETCH_ABI_LIST_SUCCESS = "FETCH_ABI_LIST_SUCCESS";
export const FETCH_ABI_LIST_FAILURE = "FETCH_ABI_LIST_FAILURE";
export const FETCH_CAB_LIST = "FETCH_CAB_LIST";
export const FETCH_CAB_LIST_SUCCESS = "FETCH_CAB_LIST_SUCCESS";
export const FETCH_CAB_LIST_FAILURE = "FETCH_CAB_LIST_FAILURE";
